# Docs @ http://pre-commit.com/

repos:
- repo: https://github.com/kuanb/pre-commit-hooks.git
  sha: 61d0735ca8b0ce5ab8df867bc974798ba8316ee5
  hooks:
  - id: autopep8-wrapper
  - id: check-added-large-files
    args: ['--maxkb=500']
  - id: check-ast
  - id: check-byte-order-marker
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-json
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-xml
  - id: check-yaml
    args: ['--ignore-tags=!include']
  - id: debug-statements
  - id: end-of-file-fixer
  - id: fix-encoding-pragma
    args: ["--remove"]
  - id: flake8
  - id: trailing-whitespace

- repo: https://github.com/kuanb/pre-commit-python-sorter.git
  sha: 1.0.8
  hooks:
  - id: python-import-sorter
