languages:
  - python3

python:
  - 3.6
  - 3.5

services:
  - docker

before_install:
  - touch .env
  - docker build -t kuanb/test .
  - sudo apt-get -y update
  - pip install --upgrade pip
  - pip install --upgrade wheel

install:
  - docker run kuanb/test /bin/sh -c "pip install -r requirements.txt"
  - docker run kuanb/test /bin/sh -c "pip install -r requirements_dev.txt"
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt

script:
  - PYTHONPATH=. MPLBACKEND="agg" py.test -k 'not graph_tool' --verbose
  - docker run -v $PWD:/code -it kuanb/test bash -c "GRAPH_TOOL_DIR=/usr/lib/python3/dist-packages/ PYTHONPATH=. MPLBACKEND="agg" coverage run --source peartree -m py.test --verbose"

after_success:
  - coverage report -m
  - codecov
