addons:
  apt:
    packages:
    - libgdal1h
    - gdal-bin
    - libgdal-dev
    - libspatialindex-dev

language: python

python:
  - 3.6
  - 3.5

before_install:
  - sudo apt-get -y update
  - pip install --user codecov
  - pip install --upgrade pip
  - pip install --upgrade wheel

install:
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt

script:
  - PYTHONPATH=. MPLBACKEND="agg" coverage run --source peartree -m py.test --verbose

after_success:
  - coverage report -m
  - codecov
