addons:
  apt:
    packages:
    - libgdal1h
    - gdal-bin
    - libgdal-dev
    - libspatialindex-dev

services:
  - docker

before_install:
  - touch .env
  - docker build -t kuanb/test .

install:
  - docker run kuanb/test /bin/sh -c "pip install -r requirements.txt"
  - docker run kuanb/test /bin/sh -c "pip install -r requirements_dev.txt"

script:
  - docker run kuanb/test /bin/sh -c "GRAPH_TOOL_DIR=/usr/lib/python3/dist-packages/ PYTHONPATH=. MPLBACKEND="agg" coverage run --source peartree -m py.test --verbose"

after_success:
  - coverage report -m
  - codecov
