addons:
  apt:
    packages:
    - libgdal1h
    - gdal-bin
    - libgdal-dev
    - libspatialindex-dev

language: python

python:
  - 3.5

services:
  - docker

before_install:
  - touch .env
  - docker build -t ci/build .
  - sudo apt-get -y update
  - pip install --upgrade pip
  - pip install --upgrade wheel

install:
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt
  - pip install osmnx matplotlib

script:
  - PYTHONPATH=. MPLBACKEND="agg" py.test -k 'not graph_tool' --verbose
  - find . | grep -E "(__pycache__|\.pyc|\.pyo$)" | xargs rm -rf
  - ci_env=`bash <(curl -s https://codecov.io/env)`
  - docker run $ci_env -v $PWD:/code -it ci/build bash -c "GRAPH_TOOL_DIR=/usr/lib/python3/dist-packages/ PYTHONPATH=. MPLBACKEND="agg" coverage run --source peartree -m py.test --verbose"

after_success:
  - docker run $ci_env -v $PWD:/code -it ci/build bash -c "coverage report -m"
  - docker run $ci_env -v $PWD:/code -it ci/build bash -c "bash <(curl -s https://codecov.io/bash)"
